standard importing the menu and nutritional info for the dish in the menu

In [136]:
import pandas as pd
MENU_LATEST= r'C:/Users/Penelope/Documents/GitHub/Weplate/backend/backend_data_parsing/babson/master_menu/menu.csv'
NUTRITION_TABLE_LATEST = r'C:/Users/Penelope/Documents/GitHub/Weplate/backend/backend_data_parsing/babson/master_nutrition/nutrition_table.csv'
menu = pd.read_csv(MENU_LATEST)
dish = pd.read_csv(NUTRITION_TABLE_LATEST)
items = eval(menu.loc[2, 'items'])
print(items)

[1208, 1236, 1238, 1223, 1240, 1266, 1293, 1276, 1156, 1182, 1146, 1149, 1172, 1110, 1123, 1102, 1119, 1085, 1077, 1068]


In [54]:
menu.head(3) #no special meaning, just showing you what is menu 

group             timestamp                                  name  \
0  afterlunch  2022-03-06 14:30:00Z  Afterlunch on Sunday, March 06, 2022   
1   breakfast  2022-03-06 07:30:00Z   Breakfast on Sunday, March 06, 2022   
2      dinner  2022-03-06 16:30:00Z      Dinner on Sunday, March 06, 2022   

                                               items  week_num  \
0                                                 []         9   
1         [1047, 1021, 1014, 1036, 1037, 1056, 1040]         9   
2  [1208, 1236, 1238, 1223, 1240, 1266, 1293, 127...         9   

                                    items_recipe_num    pk  
0          ['102407', '44726.1', '14920', '82258.7']  1000  
1  ['2032.23', '18451.22', '616.22', '1125.10', '...  1001  
2  ['102098', '4490', '2402', '103772', '33992.8'...  1002

In [166]:
#create a fake class for rapid testing, rather than trying to integrate with the existing code

class dish_nutrient:
    """
    @params: protein - scalar, value from nutritional table
    @params: carbohydrate - scalar, value from nutritional table
    @params: calories - scalar, value from nutritional table
    @params: total_fat - scalar, value from nutritional table
    @params: saturated_fat - scalar, value from nutritional table
    @params: volume - scalar, portion_volume value from nutritional table 
    @params: pk - scalar, pk of the dish 
    @params: max_pieces - scalar, value from nutritional table
    """
    def __init__(self, protein, carbohydrate, calories, total_fat, saturated_fat, volume, pk, max_pieces):
        self.protein = protein
        self.carbohydrate = carbohydrate
        self.calories = calories
        self.total_fat = total_fat
        self.saturated_fat = saturated_fat
        self.volume = volume
        self.pk = pk
        self.max_pieces = max_pieces
    def normalized_nutrients(self):
        """
        Normalize the nutrients value from the nutrition table
        @return: normalized protein, carbohydrate, calories, total_fat, saturated_fat, pk, max_pieces 
        Note that if it's not a discrete item, the max_pieces is set to int(0)
        """ 
        import numpy as np
        if self.volume > 0:
            return np.array([self.protein/self.volume, 
                             self.carbohydrate/self.volume,
                             self.calories/self.volume,
                             self.total_fat/self.volume,
                             self.saturated_fat/self.volume, int(self.pk),int(0)])
        else:
            return np.array([self.protein/self.volume*-1, 
                             self.carbohydrate/self.volume*-1,
                             self.calories/self.volume*-1,
                             self.total_fat/self.volume*-1,
                             self.saturated_fat/self.volume*-1,  int(self.pk), int(self.max_pieces)])

In [167]:
# This is just to create a list of dish_nutrient class objects for all the dishes in that meal
dish_nutrients = []
for i in items:  
    protein, carbohydrate, calories, total_fat, saturated_fat, portion_volume, max_pieces = dish[dish.pk == i][['protein', 'carbohydrate', 'calories', 'total_fat', 'saturated_fat', 'portion_volume', 'max_pieces']].values.squeeze(0)
    dish_nutrients.append(dish_nutrient(protein, carbohydrate, calories, total_fat, saturated_fat, portion_volume, i, max_pieces))
print(dish_nutrients)


[<__main__.dish_nutrient object at 0x0000017AC48F7640>, <__main__.dish_nutrient object at 0x0000017AA5E2E250>, <__main__.dish_nutrient object at 0x0000017AA645A250>, <__main__.dish_nutrient object at 0x0000017AA645AA60>, <__main__.dish_nutrient object at 0x0000017AC4901430>, <__main__.dish_nutrient object at 0x0000017AC4901640>, <__main__.dish_nutrient object at 0x0000017AC4901F10>, <__main__.dish_nutrient object at 0x0000017AC48F7130>, <__main__.dish_nutrient object at 0x0000017AC48F7DF0>, <__main__.dish_nutrient object at 0x0000017AC48F71F0>, <__main__.dish_nutrient object at 0x0000017AC48F7C70>, <__main__.dish_nutrient object at 0x0000017AC48F72B0>, <__main__.dish_nutrient object at 0x0000017AC48F7A30>, <__main__.dish_nutrient object at 0x0000017AC48F71C0>, <__main__.dish_nutrient object at 0x0000017AC48F7100>, <__main__.dish_nutrient object at 0x0000017AC48F76D0>, <__main__.dish_nutrient object at 0x0000017AC48F7A00>, <__main__.dish_nutrient object at 0x0000017AC48F7C10>, <__main__

In [168]:
# This is just to create a list of possible combinations of dish_nutrient objects for that particular meal
import itertools
combinations = []
for ind_item, i in enumerate(dish_nutrients):
    item_copy = dish_nutrients.copy()
    item_copy.pop(ind_item)
    a = list(itertools.combinations(item_copy, 2))
    a = [(dish_nutrients[ind_item],) + aa for aa in a]
    combinations.extend(a)
print(len(combinations))

3420


In [169]:
combinations[350][0].max_pieces

0.0

In [219]:
import numpy as np
import time 
from scipy.optimize import minimize
from scipy.spatial import distance


def pick_meal(combination):
    """
    Calculate the volume of the three different portions 
    @params: combination of the dish_nutrient objects 
    @returns: an array 
    [pk of dish in large, pk of dish in small 1, pk of dish in small 2, 
    volume of dish in large, volume of dish in small 1, volume of dish in small 2, 
    nutrients of all these dishes, performance of the objective functions]
    Note: the order of nutrients here: [protein, carbohydrate, calories, total_fat, saturated_fat]
    Since it's multiprocess, so I have to import packages and dependent functions inside pick_meal
    """ 
    import numpy as np
    from scipy.optimize import minimize
    from scipy.spatial import distance
    
    def my_distance(current_x, bounds, weights_below, weights_above):
        """
        Cost function - how far the particular nutrient is off from the lower-bound or upper-bound
        @params: current_x - array, amount of nutrients that current volume and combination offer
        @params: bounds - array, the lower and upper bounds of particular nutrient
        @params: weights_below - array, the penalty weight for particular nutrient falling below lower-bound
        @params: weights_above - array, the penalty weight for particular nutrient going above upper-bound
        @returns: dist - scalar, which is the summation of how far all nutrients are off from target bound
        """ 
        dist = 0
        for indx,  cx in enumerate(current_x):
            if cx > bounds[indx][0] and cx < bounds[indx][1]:
                dist += 0
            elif cx > bounds[indx][1]:
                dist += weights_above[indx]*(cx - bounds[indx][1])**2
            else:
                dist += weights_below[indx]*(bounds[indx][0] - cx)**2
        return dist

    #for i in combinations: 
    dish_1 = combination[0].normalized_nutrients()[:-2]
    dish_2 = combination[1].normalized_nutrients()[:-2]
    dish_3 = combination[2].normalized_nutrients()[:-2]
    dishes = np.array([dish_1, dish_2, dish_3]).transpose()

    # should input the boundary somehow later, but just trying to reduce the complexity in testing
    bound_protein = (26.1, 32.6)
    bound_carbohydrate = (195.7, 205.5)
    bound_calories = (817.9, 1106.6)
    bound_total_fat = (26.7, 32.1)
    bound_saturated_fat = (0, 10.7)
    
    wb = [20, 50, 1, 50, 1.5*50]
    wa = [20, 8, 1, 50, 1.5*50]
    x0 = np.zeros(3)
    
    if combination[0].max_pieces == 0: 
        bnd1 = (300, 610)
        x0[0] = 300
    else:
        bnd1 = (0, int(combination[0].max_pieces))
        x0[0] = 1
        
    if combination[1].max_pieces == 0: 
        bnd2 = (50, 270)
        x0[1] = 150
    else:
        bnd2 = (0, int(combination[1].max_pieces))
        x0[1] = 1
        
    if combination[2].max_pieces == 0: 
        bnd3 = (50, 270)
        x0[2] = 100
    else:
        bnd3 = (0, int(combination[2].max_pieces))
        x0[2] = 1
        
    bounds = [bound_protein, bound_carbohydrate, bound_calories, bound_total_fat, bound_saturated_fat]
    bounds_lower = [bound_protein[0], bound_carbohydrate[0], bound_calories[0], bound_total_fat[0], bound_saturated_fat[0]]
    bounds_upper = [bound_protein[1], bound_carbohydrate[1], bound_calories[1], bound_total_fat[1], bound_saturated_fat[1]]

    my_objective = lambda x: my_distance(np.dot(dishes,x) , bounds, wb, wa)
    constraint_lower = lambda x: np.dot(dishes,x) - bounds_lower
    constraint_upper = lambda x: bounds_upper - np.dot(dishes,x)
    bnds = (bnd1,bnd2,bnd3) 
       
    con11 = {'type': 'ineq', 'fun': constraint_lower}
    con12 = {'type': 'ineq', 'fun': constraint_upper}

    cons = ([con11, con12])
    solution = minimize(my_objective,x0, method='SLSQP', bounds=bnds, constraints=cons,options={'maxiter': 5000, 'ftol': 1e-06})
    x = solution.x
    x = [round(xx,0) for xx in x]
    solution = [combination[0].pk, combination[1].pk, combination[2].pk, x[0], x[1], x[2], np.dot(dishes,x), my_objective(x)]

    return solution



In [223]:
from multiprocess import Pool

start_time = time.perf_counter()
with Pool(8) as p:
    result = p.map(pick_meal, combinations)

result = sorted(result, key=lambda x : x[-1])
print(time.perf_counter() - start_time)
print(result)
#bound_protein, bound_carbohydrate, bound_calories, bound_total_fat, bound_saturated_fat

1.734713499999998
[[1238, 1149, 1102, 510.0, 270.0, 1.0, array([  45.81006644,  180.86883527, 1126.54961367,   26.29986305,
          8.        ]), 14894.282029264536], [1149, 1238, 1068, 610.0, 270.0, 2.0, array([  39.44308249,  183.5595381 , 1192.3428069 ,   40.33070147,
          5.        ]), 19045.1475888879], [1266, 1238, 1068, 610.0, 270.0, 2.0, array([  36.00532008,  176.68401328, 1003.26587429,   22.28244881,
          5.        ]), 19288.04957198604], [1149, 1238, 1077, 610.0, 270.0, 2.0, array([  43.44308249,  179.5595381 , 1172.3428069 ,   36.33070147,
          6.        ]), 20594.232681961075], [1266, 1238, 1085, 610.0, 270.0, 2.0, array([  38.00532008,  174.68401328, 1043.26587429,   24.28244881,
          7.        ]), 22960.16228550772], [1156, 1149, 1102, 486.0, 270.0, 1.0, array([  53.21534482,  181.1224407 , 1188.42933708,   30.20538658,
          8.        ]), 25821.151005491505], [1238, 1240, 1102, 518.0, 270.0, 1.0, array([  43.79813008,  173.02397417, 1087.66344

In [204]:
for c in combinations:
    print(c[0].pk, c[1].pk, c[2].pk)
    print(c[0].volume, c[1].volume, c[2].volume)
    print(c[0].normalized_nutrients())
    if c[0].normalized_nutrients()[-1] == 0:
        print(1)
    pick_meal(c)

1208 1236 1238
709.764 118.294 118.294
[7.46727081e-02 2.25427043e-02 6.48102750e-01 2.81783804e-02
 1.26802712e-02 1.20800000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1208 1236 1223
709.764 118.294 157.7253333
[7.46727081e-02 2.25427043e-02 6.48102750e-01 2.81783804e-02
 1.26802712e-02 1.20800000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1208 1236 1240
709.764 118.294 118.294
[7.46727081e-02 2.25427043e-02 6.48102750e-01 2.81783804e-02
 1.26802712e-02 1.20800000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1208 1236 1266
709.764 118.294 177.441
[7.46727081e-02 2.25427043e-02 6.48102750e-01 2.81783804e-02
 1.26802712e-02 1.20800000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1208 1236 1293
709.764 118.294 118.294
[7.46727081e-02 2.25427043e-02 6.48102750e-01 2.81783804e-02
 1.26802712e-02 1.20800000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 15

1208 1293 1085
709.764 118.294 -1.0
[7.46727081e-02 2.25427043e-02 6.48102750e-01 2.81783804e-02
 1.26802712e-02 1.20800000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1208 1293 1077
709.764 118.294 -1.0
[7.46727081e-02 2.25427043e-02 6.48102750e-01 2.81783804e-02
 1.26802712e-02 1.20800000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1208 1293 1068
709.764 118.294 -1.0
[7.46727081e-02 2.25427043e-02 6.48102750e-01 2.81783804e-02
 1.26802712e-02 1.20800000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1208 1276 1156
709.764 236.588 118.294
[7.46727081e-02 2.25427043e-02 6.48102750e-01 2.81783804e-02
 1.26802712e-02 1.20800000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1208 1276 1182
709.764 236.588 118.294
[7.46727081e-02 2.25427043e-02 6.48102750e-01 2.81783804e-02
 1.26802712e-02 1.20800000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1208 1276 114

1208 1172 1110
709.764 177.441 88.7205
[7.46727081e-02 2.25427043e-02 6.48102750e-01 2.81783804e-02
 1.26802712e-02 1.20800000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1208 1172 1123
709.764 177.441 177.441
[7.46727081e-02 2.25427043e-02 6.48102750e-01 2.81783804e-02
 1.26802712e-02 1.20800000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1208 1172 1102
709.764 177.441 -1.0
[7.46727081e-02 2.25427043e-02 6.48102750e-01 2.81783804e-02
 1.26802712e-02 1.20800000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1208 1172 1119
709.764 177.441 -1.0
[7.46727081e-02 2.25427043e-02 6.48102750e-01 2.81783804e-02
 1.26802712e-02 1.20800000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1208 1172 1085
709.764 177.441 -1.0
[7.46727081e-02 2.25427043e-02 6.48102750e-01 2.81783804e-02
 1.26802712e-02 1.20800000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1208 1172 107

1236 1238 1266
118.294 118.294 177.441
[5.07210848e-02 1.69070283e-01 2.28244881e+00 1.60616768e-01
 3.80408136e-02 1.23600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1236 1238 1293
118.294 118.294 118.294
[5.07210848e-02 1.69070283e-01 2.28244881e+00 1.60616768e-01
 3.80408136e-02 1.23600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1236 1238 1276
118.294 118.294 236.588
[5.07210848e-02 1.69070283e-01 2.28244881e+00 1.60616768e-01
 3.80408136e-02 1.23600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1236 1238 1156
118.294 118.294 118.294
[5.07210848e-02 1.69070283e-01 2.28244881e+00 1.60616768e-01
 3.80408136e-02 1.23600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1236 1238 1182
118.294 118.294 118.294
[5.07210848e-02 1.69070283e-01 2.28244881e+00 1.60616768e-01
 3.80408136e-02 1.23600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 1

1236 1266 1146
118.294 177.441 118.294
[5.07210848e-02 1.69070283e-01 2.28244881e+00 1.60616768e-01
 3.80408136e-02 1.23600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1236 1266 1149
118.294 177.441 118.294
[5.07210848e-02 1.69070283e-01 2.28244881e+00 1.60616768e-01
 3.80408136e-02 1.23600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1236 1266 1172
118.294 177.441 177.441
[5.07210848e-02 1.69070283e-01 2.28244881e+00 1.60616768e-01
 3.80408136e-02 1.23600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1236 1266 1110
118.294 177.441 88.7205
[5.07210848e-02 1.69070283e-01 2.28244881e+00 1.60616768e-01
 3.80408136e-02 1.23600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1236 1266 1123
118.294 177.441 177.441
[5.07210848e-02 1.69070283e-01 2.28244881e+00 1.60616768e-01
 3.80408136e-02 1.23600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 1

1236 1182 1110
118.294 118.294 88.7205
[5.07210848e-02 1.69070283e-01 2.28244881e+00 1.60616768e-01
 3.80408136e-02 1.23600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1236 1182 1123
118.294 118.294 177.441
[5.07210848e-02 1.69070283e-01 2.28244881e+00 1.60616768e-01
 3.80408136e-02 1.23600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1236 1182 1102
118.294 118.294 -1.0
[5.07210848e-02 1.69070283e-01 2.28244881e+00 1.60616768e-01
 3.80408136e-02 1.23600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1236 1182 1119
118.294 118.294 -1.0
[5.07210848e-02 1.69070283e-01 2.28244881e+00 1.60616768e-01
 3.80408136e-02 1.23600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1236 1182 1085
118.294 118.294 -1.0
[5.07210848e-02 1.69070283e-01 2.28244881e+00 1.60616768e-01
 3.80408136e-02 1.23600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1236 1182 107

[300. 150. 100.]
1238 1208 1156
118.294 709.764 118.294
[3.38140565e-02 1.60616768e-01 8.45351413e-01 8.45351413e-03
 0.00000000e+00 1.23800000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1238 1208 1182
118.294 709.764 118.294
[3.38140565e-02 1.60616768e-01 8.45351413e-01 8.45351413e-03
 0.00000000e+00 1.23800000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1238 1208 1146
118.294 709.764 118.294
[3.38140565e-02 1.60616768e-01 8.45351413e-01 8.45351413e-03
 0.00000000e+00 1.23800000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1238 1208 1149
118.294 709.764 118.294
[3.38140565e-02 1.60616768e-01 8.45351413e-01 8.45351413e-03
 0.00000000e+00 1.23800000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1238 1208 1172
118.294 709.764 177.441
[3.38140565e-02 1.60616768e-01 8.45351413e-01 8.45351413e-03
 0.00000000e+00 1.23800000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 2

1238 1240 1293
118.294 118.294 118.294
[3.38140565e-02 1.60616768e-01 8.45351413e-01 8.45351413e-03
 0.00000000e+00 1.23800000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1238 1240 1276
118.294 118.294 236.588
[3.38140565e-02 1.60616768e-01 8.45351413e-01 8.45351413e-03
 0.00000000e+00 1.23800000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1238 1240 1156
118.294 118.294 118.294
[3.38140565e-02 1.60616768e-01 8.45351413e-01 8.45351413e-03
 0.00000000e+00 1.23800000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1238 1240 1182
118.294 118.294 118.294
[3.38140565e-02 1.60616768e-01 8.45351413e-01 8.45351413e-03
 0.00000000e+00 1.23800000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1238 1240 1146
118.294 118.294 118.294
[3.38140565e-02 1.60616768e-01 8.45351413e-01 8.45351413e-03
 0.00000000e+00 1.23800000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 1

[300. 150. 100.]
1238 1156 1149
118.294 118.294 118.294
[3.38140565e-02 1.60616768e-01 8.45351413e-01 8.45351413e-03
 0.00000000e+00 1.23800000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1238 1156 1172
118.294 118.294 177.441
[3.38140565e-02 1.60616768e-01 8.45351413e-01 8.45351413e-03
 0.00000000e+00 1.23800000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1238 1156 1110
118.294 118.294 88.7205
[3.38140565e-02 1.60616768e-01 8.45351413e-01 8.45351413e-03
 0.00000000e+00 1.23800000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1238 1156 1123
118.294 118.294 177.441
[3.38140565e-02 1.60616768e-01 8.45351413e-01 8.45351413e-03
 0.00000000e+00 1.23800000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1238 1156 1102
118.294 118.294 -1.0
[3.38140565e-02 1.60616768e-01 8.45351413e-01 8.45351413e-03
 0.00000000e+00 1.23800000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[

1238 1110 1102
118.294 88.7205 -1.0
[3.38140565e-02 1.60616768e-01 8.45351413e-01 8.45351413e-03
 0.00000000e+00 1.23800000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1238 1110 1119
118.294 88.7205 -1.0
[3.38140565e-02 1.60616768e-01 8.45351413e-01 8.45351413e-03
 0.00000000e+00 1.23800000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1238 1110 1085
118.294 88.7205 -1.0
[3.38140565e-02 1.60616768e-01 8.45351413e-01 8.45351413e-03
 0.00000000e+00 1.23800000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1238 1110 1077
118.294 88.7205 -1.0
[3.38140565e-02 1.60616768e-01 8.45351413e-01 8.45351413e-03
 0.00000000e+00 1.23800000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1238 1110 1068
118.294 88.7205 -1.0
[3.38140565e-02 1.60616768e-01 8.45351413e-01 8.45351413e-03
 0.00000000e+00 1.23800000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1238 1123 1102
118.294 17

1223 1238 1102
157.7253333 118.294 -1.0
[1.26802712e-02 5.70612204e-02 3.80408136e-01 1.90204068e-02
 0.00000000e+00 1.22300000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1223 1238 1119
157.7253333 118.294 -1.0
[1.26802712e-02 5.70612204e-02 3.80408136e-01 1.90204068e-02
 0.00000000e+00 1.22300000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1223 1238 1085
157.7253333 118.294 -1.0
[1.26802712e-02 5.70612204e-02 3.80408136e-01 1.90204068e-02
 0.00000000e+00 1.22300000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1223 1238 1077
157.7253333 118.294 -1.0
[1.26802712e-02 5.70612204e-02 3.80408136e-01 1.90204068e-02
 0.00000000e+00 1.22300000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1223 1238 1068
157.7253333 118.294 -1.0
[1.26802712e-02 5.70612204e-02 3.80408136e-01 1.90204068e-02
 0.00000000e+00 1.22300000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1223 

1223 1156 1119
157.7253333 118.294 -1.0
[1.26802712e-02 5.70612204e-02 3.80408136e-01 1.90204068e-02
 0.00000000e+00 1.22300000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1223 1156 1085
157.7253333 118.294 -1.0
[1.26802712e-02 5.70612204e-02 3.80408136e-01 1.90204068e-02
 0.00000000e+00 1.22300000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1223 1156 1077
157.7253333 118.294 -1.0
[1.26802712e-02 5.70612204e-02 3.80408136e-01 1.90204068e-02
 0.00000000e+00 1.22300000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1223 1156 1068
157.7253333 118.294 -1.0
[1.26802712e-02 5.70612204e-02 3.80408136e-01 1.90204068e-02
 0.00000000e+00 1.22300000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1223 1182 1146
157.7253333 118.294 118.294
[1.26802712e-02 5.70612204e-02 3.80408136e-01 1.90204068e-02
 0.00000000e+00 1.22300000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]

1240 1208 1266
118.294 709.764 177.441
[8.45351413e-03 8.45351413e-02 5.91745989e-01 2.53605424e-02
 0.00000000e+00 1.24000000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1240 1208 1293
118.294 709.764 118.294
[8.45351413e-03 8.45351413e-02 5.91745989e-01 2.53605424e-02
 0.00000000e+00 1.24000000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1240 1208 1276
118.294 709.764 236.588
[8.45351413e-03 8.45351413e-02 5.91745989e-01 2.53605424e-02
 0.00000000e+00 1.24000000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1240 1208 1156
118.294 709.764 118.294
[8.45351413e-03 8.45351413e-02 5.91745989e-01 2.53605424e-02
 0.00000000e+00 1.24000000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1240 1208 1182
118.294 709.764 118.294
[8.45351413e-03 8.45351413e-02 5.91745989e-01 2.53605424e-02
 0.00000000e+00 1.24000000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 1

118.294 157.7253333 177.441
[8.45351413e-03 8.45351413e-02 5.91745989e-01 2.53605424e-02
 0.00000000e+00 1.24000000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1240 1223 1102
118.294 157.7253333 -1.0
[8.45351413e-03 8.45351413e-02 5.91745989e-01 2.53605424e-02
 0.00000000e+00 1.24000000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1240 1223 1119
118.294 157.7253333 -1.0
[8.45351413e-03 8.45351413e-02 5.91745989e-01 2.53605424e-02
 0.00000000e+00 1.24000000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1240 1223 1085
118.294 157.7253333 -1.0
[8.45351413e-03 8.45351413e-02 5.91745989e-01 2.53605424e-02
 0.00000000e+00 1.24000000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1240 1223 1077
118.294 157.7253333 -1.0
[8.45351413e-03 8.45351413e-02 5.91745989e-01 2.53605424e-02
 0.00000000e+00 1.24000000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1240 1223 1068

((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1240 1182 1068
118.294 118.294 -1.0
[8.45351413e-03 8.45351413e-02 5.91745989e-01 2.53605424e-02
 0.00000000e+00 1.24000000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1240 1146 1149
118.294 118.294 118.294
[8.45351413e-03 8.45351413e-02 5.91745989e-01 2.53605424e-02
 0.00000000e+00 1.24000000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1240 1146 1172
118.294 118.294 177.441
[8.45351413e-03 8.45351413e-02 5.91745989e-01 2.53605424e-02
 0.00000000e+00 1.24000000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1240 1146 1110
118.294 118.294 88.7205
[8.45351413e-03 8.45351413e-02 5.91745989e-01 2.53605424e-02
 0.00000000e+00 1.24000000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1240 1146 1123
118.294 118.294 177.441
[8.45351413e-03 8.45351413e-02 5.91745989e-01 2.53605424e-02
 0.00000000e+00 1.24000000e+03 0.00000000e+00]
1
((30

[300. 150.   1.]
1266 1208 1119
177.441 709.764 -1.0
[1.12713522e-02 1.07077846e-01 4.50854087e-01 0.00000000e+00
 0.00000000e+00 1.26600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1266 1208 1085
177.441 709.764 -1.0
[1.12713522e-02 1.07077846e-01 4.50854087e-01 0.00000000e+00
 0.00000000e+00 1.26600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1266 1208 1077
177.441 709.764 -1.0
[1.12713522e-02 1.07077846e-01 4.50854087e-01 0.00000000e+00
 0.00000000e+00 1.26600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1266 1208 1068
177.441 709.764 -1.0
[1.12713522e-02 1.07077846e-01 4.50854087e-01 0.00000000e+00
 0.00000000e+00 1.26600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1266 1236 1238
177.441 118.294 118.294
[1.12713522e-02 1.07077846e-01 4.50854087e-01 0.00000000e+00
 0.00000000e+00 1.26600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
12

[300. 150.   1.]
1266 1223 1077
177.441 157.7253333 -1.0
[1.12713522e-02 1.07077846e-01 4.50854087e-01 0.00000000e+00
 0.00000000e+00 1.26600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1266 1223 1068
177.441 157.7253333 -1.0
[1.12713522e-02 1.07077846e-01 4.50854087e-01 0.00000000e+00
 0.00000000e+00 1.26600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1266 1240 1293
177.441 118.294 118.294
[1.12713522e-02 1.07077846e-01 4.50854087e-01 0.00000000e+00
 0.00000000e+00 1.26600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1266 1240 1276
177.441 118.294 236.588
[1.12713522e-02 1.07077846e-01 4.50854087e-01 0.00000000e+00
 0.00000000e+00 1.26600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1266 1240 1156
177.441 118.294 118.294
[1.12713522e-02 1.07077846e-01 4.50854087e-01 0.00000000e+00
 0.00000000e+00 1.26600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))

1266 1182 1077
177.441 118.294 -1.0
[1.12713522e-02 1.07077846e-01 4.50854087e-01 0.00000000e+00
 0.00000000e+00 1.26600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1266 1182 1068
177.441 118.294 -1.0
[1.12713522e-02 1.07077846e-01 4.50854087e-01 0.00000000e+00
 0.00000000e+00 1.26600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1266 1146 1149
177.441 118.294 118.294
[1.12713522e-02 1.07077846e-01 4.50854087e-01 0.00000000e+00
 0.00000000e+00 1.26600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1266 1146 1172
177.441 118.294 177.441
[1.12713522e-02 1.07077846e-01 4.50854087e-01 0.00000000e+00
 0.00000000e+00 1.26600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1266 1146 1110
177.441 118.294 88.7205
[1.12713522e-02 1.07077846e-01 4.50854087e-01 0.00000000e+00
 0.00000000e+00 1.26600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1266 11

1293 1208 1110
118.294 709.764 88.7205
[1.18349198e-01 7.60816271e-02 1.35256226e+00 6.76281130e-02
 4.22675706e-03 1.29300000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1293 1208 1123
118.294 709.764 177.441
[1.18349198e-01 7.60816271e-02 1.35256226e+00 6.76281130e-02
 4.22675706e-03 1.29300000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1293 1208 1102
118.294 709.764 -1.0
[1.18349198e-01 7.60816271e-02 1.35256226e+00 6.76281130e-02
 4.22675706e-03 1.29300000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1293 1208 1119
118.294 709.764 -1.0
[1.18349198e-01 7.60816271e-02 1.35256226e+00 6.76281130e-02
 4.22675706e-03 1.29300000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1293 1208 1085
118.294 709.764 -1.0
[1.18349198e-01 7.60816271e-02 1.35256226e+00 6.76281130e-02
 4.22675706e-03 1.29300000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1293 1208 107

[1.18349198e-01 7.60816271e-02 1.35256226e+00 6.76281130e-02
 4.22675706e-03 1.29300000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1293 1223 1077
118.294 157.7253333 -1.0
[1.18349198e-01 7.60816271e-02 1.35256226e+00 6.76281130e-02
 4.22675706e-03 1.29300000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1293 1223 1068
118.294 157.7253333 -1.0
[1.18349198e-01 7.60816271e-02 1.35256226e+00 6.76281130e-02
 4.22675706e-03 1.29300000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1293 1240 1266
118.294 118.294 177.441
[1.18349198e-01 7.60816271e-02 1.35256226e+00 6.76281130e-02
 4.22675706e-03 1.29300000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1293 1240 1276
118.294 118.294 236.588
[1.18349198e-01 7.60816271e-02 1.35256226e+00 6.76281130e-02
 4.22675706e-03 1.29300000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1293 1240 1156
118.294 118.294 118.294
[1

1293 1156 1182
118.294 118.294 118.294
[1.18349198e-01 7.60816271e-02 1.35256226e+00 6.76281130e-02
 4.22675706e-03 1.29300000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1293 1156 1146
118.294 118.294 118.294
[1.18349198e-01 7.60816271e-02 1.35256226e+00 6.76281130e-02
 4.22675706e-03 1.29300000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1293 1156 1149
118.294 118.294 118.294
[1.18349198e-01 7.60816271e-02 1.35256226e+00 6.76281130e-02
 4.22675706e-03 1.29300000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1293 1156 1172
118.294 118.294 177.441
[1.18349198e-01 7.60816271e-02 1.35256226e+00 6.76281130e-02
 4.22675706e-03 1.29300000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1293 1156 1110
118.294 118.294 88.7205
[1.18349198e-01 7.60816271e-02 1.35256226e+00 6.76281130e-02
 4.22675706e-03 1.29300000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 1

118.294 88.7205 177.441
[1.18349198e-01 7.60816271e-02 1.35256226e+00 6.76281130e-02
 4.22675706e-03 1.29300000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1293 1110 1102
118.294 88.7205 -1.0
[1.18349198e-01 7.60816271e-02 1.35256226e+00 6.76281130e-02
 4.22675706e-03 1.29300000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1293 1110 1119
118.294 88.7205 -1.0
[1.18349198e-01 7.60816271e-02 1.35256226e+00 6.76281130e-02
 4.22675706e-03 1.29300000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1293 1110 1085
118.294 88.7205 -1.0
[1.18349198e-01 7.60816271e-02 1.35256226e+00 6.76281130e-02
 4.22675706e-03 1.29300000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1293 1110 1077
118.294 88.7205 -1.0
[1.18349198e-01 7.60816271e-02 1.35256226e+00 6.76281130e-02
 4.22675706e-03 1.29300000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1293 1110 1068
118.294 88.7205 -1.

1276 1236 1110
236.588 118.294 88.7205
[1.26802712e-02 2.53605424e-02 9.29886554e-01 8.87618983e-02
 1.26802712e-02 1.27600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1276 1236 1123
236.588 118.294 177.441
[1.26802712e-02 2.53605424e-02 9.29886554e-01 8.87618983e-02
 1.26802712e-02 1.27600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1276 1236 1102
236.588 118.294 -1.0
[1.26802712e-02 2.53605424e-02 9.29886554e-01 8.87618983e-02
 1.26802712e-02 1.27600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1276 1236 1119
236.588 118.294 -1.0
[1.26802712e-02 2.53605424e-02 9.29886554e-01 8.87618983e-02
 1.26802712e-02 1.27600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1276 1236 1085
236.588 118.294 -1.0
[1.26802712e-02 2.53605424e-02 9.29886554e-01 8.87618983e-02
 1.26802712e-02 1.27600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1276 1236 107

1276 1240 1077
236.588 118.294 -1.0
[1.26802712e-02 2.53605424e-02 9.29886554e-01 8.87618983e-02
 1.26802712e-02 1.27600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1276 1240 1068
236.588 118.294 -1.0
[1.26802712e-02 2.53605424e-02 9.29886554e-01 8.87618983e-02
 1.26802712e-02 1.27600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1276 1266 1293
236.588 177.441 118.294
[1.26802712e-02 2.53605424e-02 9.29886554e-01 8.87618983e-02
 1.26802712e-02 1.27600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1276 1266 1156
236.588 177.441 118.294
[1.26802712e-02 2.53605424e-02 9.29886554e-01 8.87618983e-02
 1.26802712e-02 1.27600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1276 1266 1182
236.588 177.441 118.294
[1.26802712e-02 2.53605424e-02 9.29886554e-01 8.87618983e-02
 1.26802712e-02 1.27600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1276 12

[300. 150.   1.]
1276 1182 1119
236.588 118.294 -1.0
[1.26802712e-02 2.53605424e-02 9.29886554e-01 8.87618983e-02
 1.26802712e-02 1.27600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1276 1182 1085
236.588 118.294 -1.0
[1.26802712e-02 2.53605424e-02 9.29886554e-01 8.87618983e-02
 1.26802712e-02 1.27600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1276 1182 1077
236.588 118.294 -1.0
[1.26802712e-02 2.53605424e-02 9.29886554e-01 8.87618983e-02
 1.26802712e-02 1.27600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1276 1182 1068
236.588 118.294 -1.0
[1.26802712e-02 2.53605424e-02 9.29886554e-01 8.87618983e-02
 1.26802712e-02 1.27600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1276 1146 1149
236.588 118.294 118.294
[1.26802712e-02 2.53605424e-02 9.29886554e-01 8.87618983e-02
 1.26802712e-02 1.27600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
12

((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1156 1208 1182
118.294 709.764 118.294
[5.07210848e-02 1.69070283e-01 1.01442170e+00 1.69070283e-02
 0.00000000e+00 1.15600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1156 1208 1146
118.294 709.764 118.294
[5.07210848e-02 1.69070283e-01 1.01442170e+00 1.69070283e-02
 0.00000000e+00 1.15600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1156 1208 1149
118.294 709.764 118.294
[5.07210848e-02 1.69070283e-01 1.01442170e+00 1.69070283e-02
 0.00000000e+00 1.15600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1156 1208 1172
118.294 709.764 177.441
[5.07210848e-02 1.69070283e-01 1.01442170e+00 1.69070283e-02
 0.00000000e+00 1.15600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1156 1208 1110
118.294 709.764 88.7205
[5.07210848e-02 1.69070283e-01 1.01442170e+00 1.69070283e-02
 0.00000000e+00 1.15600000e+03 0.00000000e+0

1156 1238 1077
118.294 118.294 -1.0
[5.07210848e-02 1.69070283e-01 1.01442170e+00 1.69070283e-02
 0.00000000e+00 1.15600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1156 1238 1068
118.294 118.294 -1.0
[5.07210848e-02 1.69070283e-01 1.01442170e+00 1.69070283e-02
 0.00000000e+00 1.15600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1156 1223 1240
118.294 157.7253333 118.294
[5.07210848e-02 1.69070283e-01 1.01442170e+00 1.69070283e-02
 0.00000000e+00 1.15600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1156 1223 1266
118.294 157.7253333 177.441
[5.07210848e-02 1.69070283e-01 1.01442170e+00 1.69070283e-02
 0.00000000e+00 1.15600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1156 1223 1293
118.294 157.7253333 118.294
[5.07210848e-02 1.69070283e-01 1.01442170e+00 1.69070283e-02
 0.00000000e+00 1.15600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 1

1156 1293 1077
118.294 118.294 -1.0
[5.07210848e-02 1.69070283e-01 1.01442170e+00 1.69070283e-02
 0.00000000e+00 1.15600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1156 1293 1068
118.294 118.294 -1.0
[5.07210848e-02 1.69070283e-01 1.01442170e+00 1.69070283e-02
 0.00000000e+00 1.15600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1156 1276 1182
118.294 236.588 118.294
[5.07210848e-02 1.69070283e-01 1.01442170e+00 1.69070283e-02
 0.00000000e+00 1.15600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1156 1276 1146
118.294 236.588 118.294
[5.07210848e-02 1.69070283e-01 1.01442170e+00 1.69070283e-02
 0.00000000e+00 1.15600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1156 1276 1149
118.294 236.588 118.294
[5.07210848e-02 1.69070283e-01 1.01442170e+00 1.69070283e-02
 0.00000000e+00 1.15600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1156 12

1156 1110 1068
118.294 88.7205 -1.0
[5.07210848e-02 1.69070283e-01 1.01442170e+00 1.69070283e-02
 0.00000000e+00 1.15600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1156 1123 1102
118.294 177.441 -1.0
[5.07210848e-02 1.69070283e-01 1.01442170e+00 1.69070283e-02
 0.00000000e+00 1.15600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1156 1123 1119
118.294 177.441 -1.0
[5.07210848e-02 1.69070283e-01 1.01442170e+00 1.69070283e-02
 0.00000000e+00 1.15600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1156 1123 1085
118.294 177.441 -1.0
[5.07210848e-02 1.69070283e-01 1.01442170e+00 1.69070283e-02
 0.00000000e+00 1.15600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1156 1123 1077
118.294 177.441 -1.0
[5.07210848e-02 1.69070283e-01 1.01442170e+00 1.69070283e-02
 0.00000000e+00 1.15600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1156 1123 1068
118.294 17

118.294 118.294 -1.0
[1.69070283e-02 6.76281130e-02 3.80408136e-01 1.26802712e-02
 0.00000000e+00 1.18200000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1182 1236 1068
118.294 118.294 -1.0
[1.69070283e-02 6.76281130e-02 3.80408136e-01 1.26802712e-02
 0.00000000e+00 1.18200000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1182 1238 1223
118.294 118.294 157.7253333
[1.69070283e-02 6.76281130e-02 3.80408136e-01 1.26802712e-02
 0.00000000e+00 1.18200000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1182 1238 1240
118.294 118.294 118.294
[1.69070283e-02 6.76281130e-02 3.80408136e-01 1.26802712e-02
 0.00000000e+00 1.18200000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1182 1238 1266
118.294 118.294 177.441
[1.69070283e-02 6.76281130e-02 3.80408136e-01 1.26802712e-02
 0.00000000e+00 1.18200000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1182 1238 1293
118

[300. 150. 100.]
1182 1266 1110
118.294 177.441 88.7205
[1.69070283e-02 6.76281130e-02 3.80408136e-01 1.26802712e-02
 0.00000000e+00 1.18200000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1182 1266 1123
118.294 177.441 177.441
[1.69070283e-02 6.76281130e-02 3.80408136e-01 1.26802712e-02
 0.00000000e+00 1.18200000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1182 1266 1102
118.294 177.441 -1.0
[1.69070283e-02 6.76281130e-02 3.80408136e-01 1.26802712e-02
 0.00000000e+00 1.18200000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1182 1266 1119
118.294 177.441 -1.0
[1.69070283e-02 6.76281130e-02 3.80408136e-01 1.26802712e-02
 0.00000000e+00 1.18200000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1182 1266 1085
118.294 177.441 -1.0
[1.69070283e-02 6.76281130e-02 3.80408136e-01 1.26802712e-02
 0.00000000e+00 1.18200000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   

1182 1149 1102
118.294 118.294 -1.0
[1.69070283e-02 6.76281130e-02 3.80408136e-01 1.26802712e-02
 0.00000000e+00 1.18200000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1182 1149 1119
118.294 118.294 -1.0
[1.69070283e-02 6.76281130e-02 3.80408136e-01 1.26802712e-02
 0.00000000e+00 1.18200000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1182 1149 1085
118.294 118.294 -1.0
[1.69070283e-02 6.76281130e-02 3.80408136e-01 1.26802712e-02
 0.00000000e+00 1.18200000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1182 1149 1077
118.294 118.294 -1.0
[1.69070283e-02 6.76281130e-02 3.80408136e-01 1.26802712e-02
 0.00000000e+00 1.18200000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1182 1149 1068
118.294 118.294 -1.0
[1.69070283e-02 6.76281130e-02 3.80408136e-01 1.26802712e-02
 0.00000000e+00 1.18200000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1182 1172 1110
118.294 17

1146 1236 1240
118.294 118.294 118.294
[1.69070283e-02 6.76281130e-02 5.91745989e-01 3.38140565e-02
 4.22675706e-03 1.14600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1146 1236 1266
118.294 118.294 177.441
[1.69070283e-02 6.76281130e-02 5.91745989e-01 3.38140565e-02
 4.22675706e-03 1.14600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1146 1236 1293
118.294 118.294 118.294
[1.69070283e-02 6.76281130e-02 5.91745989e-01 3.38140565e-02
 4.22675706e-03 1.14600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1146 1236 1276
118.294 118.294 236.588
[1.69070283e-02 6.76281130e-02 5.91745989e-01 3.38140565e-02
 4.22675706e-03 1.14600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1146 1236 1156
118.294 118.294 118.294
[1.69070283e-02 6.76281130e-02 5.91745989e-01 3.38140565e-02
 4.22675706e-03 1.14600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 1

1146 1240 1085
118.294 118.294 -1.0
[1.69070283e-02 6.76281130e-02 5.91745989e-01 3.38140565e-02
 4.22675706e-03 1.14600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1146 1240 1077
118.294 118.294 -1.0
[1.69070283e-02 6.76281130e-02 5.91745989e-01 3.38140565e-02
 4.22675706e-03 1.14600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1146 1240 1068
118.294 118.294 -1.0
[1.69070283e-02 6.76281130e-02 5.91745989e-01 3.38140565e-02
 4.22675706e-03 1.14600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1146 1266 1293
118.294 177.441 118.294
[1.69070283e-02 6.76281130e-02 5.91745989e-01 3.38140565e-02
 4.22675706e-03 1.14600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1146 1266 1276
118.294 177.441 236.588
[1.69070283e-02 6.76281130e-02 5.91745989e-01 3.38140565e-02
 4.22675706e-03 1.14600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1146 1266 115

1146 1149 1110
118.294 118.294 88.7205
[1.69070283e-02 6.76281130e-02 5.91745989e-01 3.38140565e-02
 4.22675706e-03 1.14600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1146 1149 1123
118.294 118.294 177.441
[1.69070283e-02 6.76281130e-02 5.91745989e-01 3.38140565e-02
 4.22675706e-03 1.14600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1146 1149 1102
118.294 118.294 -1.0
[1.69070283e-02 6.76281130e-02 5.91745989e-01 3.38140565e-02
 4.22675706e-03 1.14600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1146 1149 1119
118.294 118.294 -1.0
[1.69070283e-02 6.76281130e-02 5.91745989e-01 3.38140565e-02
 4.22675706e-03 1.14600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1146 1149 1085
118.294 118.294 -1.0
[1.69070283e-02 6.76281130e-02 5.91745989e-01 3.38140565e-02
 4.22675706e-03 1.14600000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1146 1149 107

1149 1238 1223
118.294 118.294 157.7253333
[1.69070283e-02 1.18349198e-01 7.60816271e-01 2.95872994e-02
 0.00000000e+00 1.14900000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1149 1238 1240
118.294 118.294 118.294
[1.69070283e-02 1.18349198e-01 7.60816271e-01 2.95872994e-02
 0.00000000e+00 1.14900000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1149 1238 1266
118.294 118.294 177.441
[1.69070283e-02 1.18349198e-01 7.60816271e-01 2.95872994e-02
 0.00000000e+00 1.14900000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1149 1238 1293
118.294 118.294 118.294
[1.69070283e-02 1.18349198e-01 7.60816271e-01 2.95872994e-02
 0.00000000e+00 1.14900000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1149 1238 1276
118.294 118.294 236.588
[1.69070283e-02 1.18349198e-01 7.60816271e-01 2.95872994e-02
 0.00000000e+00 1.14900000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 15

1149 1293 1156
118.294 118.294 118.294
[1.69070283e-02 1.18349198e-01 7.60816271e-01 2.95872994e-02
 0.00000000e+00 1.14900000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1149 1293 1182
118.294 118.294 118.294
[1.69070283e-02 1.18349198e-01 7.60816271e-01 2.95872994e-02
 0.00000000e+00 1.14900000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1149 1293 1146
118.294 118.294 118.294
[1.69070283e-02 1.18349198e-01 7.60816271e-01 2.95872994e-02
 0.00000000e+00 1.14900000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1149 1293 1172
118.294 118.294 177.441
[1.69070283e-02 1.18349198e-01 7.60816271e-01 2.95872994e-02
 0.00000000e+00 1.14900000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1149 1293 1110
118.294 118.294 88.7205
[1.69070283e-02 1.18349198e-01 7.60816271e-01 2.95872994e-02
 0.00000000e+00 1.14900000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 1

1149 1110 1085
118.294 88.7205 -1.0
[1.69070283e-02 1.18349198e-01 7.60816271e-01 2.95872994e-02
 0.00000000e+00 1.14900000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1149 1110 1077
118.294 88.7205 -1.0
[1.69070283e-02 1.18349198e-01 7.60816271e-01 2.95872994e-02
 0.00000000e+00 1.14900000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1149 1110 1068
118.294 88.7205 -1.0
[1.69070283e-02 1.18349198e-01 7.60816271e-01 2.95872994e-02
 0.00000000e+00 1.14900000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1149 1123 1102
118.294 177.441 -1.0
[1.69070283e-02 1.18349198e-01 7.60816271e-01 2.95872994e-02
 0.00000000e+00 1.14900000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1149 1123 1119
118.294 177.441 -1.0
[1.69070283e-02 1.18349198e-01 7.60816271e-01 2.95872994e-02
 0.00000000e+00 1.14900000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1149 1123 1085
118.294 17

[300. 150. 100.]
1172 1238 1110
177.441 118.294 88.7205
[1.12713522e-01 5.63567608e-03 1.07077846e+00 6.76281130e-02
 2.53605424e-02 1.17200000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1172 1238 1123
177.441 118.294 177.441
[1.12713522e-01 5.63567608e-03 1.07077846e+00 6.76281130e-02
 2.53605424e-02 1.17200000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1172 1238 1102
177.441 118.294 -1.0
[1.12713522e-01 5.63567608e-03 1.07077846e+00 6.76281130e-02
 2.53605424e-02 1.17200000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1172 1238 1119
177.441 118.294 -1.0
[1.12713522e-01 5.63567608e-03 1.07077846e+00 6.76281130e-02
 2.53605424e-02 1.17200000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1172 1238 1085
177.441 118.294 -1.0
[1.12713522e-01 5.63567608e-03 1.07077846e+00 6.76281130e-02
 2.53605424e-02 1.17200000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   

1172 1266 1077
177.441 177.441 -1.0
[1.12713522e-01 5.63567608e-03 1.07077846e+00 6.76281130e-02
 2.53605424e-02 1.17200000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1172 1266 1068
177.441 177.441 -1.0
[1.12713522e-01 5.63567608e-03 1.07077846e+00 6.76281130e-02
 2.53605424e-02 1.17200000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1172 1293 1276
177.441 118.294 236.588
[1.12713522e-01 5.63567608e-03 1.07077846e+00 6.76281130e-02
 2.53605424e-02 1.17200000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1172 1293 1156
177.441 118.294 118.294
[1.12713522e-01 5.63567608e-03 1.07077846e+00 6.76281130e-02
 2.53605424e-02 1.17200000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1172 1293 1182
177.441 118.294 118.294
[1.12713522e-01 5.63567608e-03 1.07077846e+00 6.76281130e-02
 2.53605424e-02 1.17200000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1172 12

1172 1146 1085
177.441 118.294 -1.0
[1.12713522e-01 5.63567608e-03 1.07077846e+00 6.76281130e-02
 2.53605424e-02 1.17200000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1172 1146 1077
177.441 118.294 -1.0
[1.12713522e-01 5.63567608e-03 1.07077846e+00 6.76281130e-02
 2.53605424e-02 1.17200000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1172 1146 1068
177.441 118.294 -1.0
[1.12713522e-01 5.63567608e-03 1.07077846e+00 6.76281130e-02
 2.53605424e-02 1.17200000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1172 1149 1110
177.441 118.294 88.7205
[1.12713522e-01 5.63567608e-03 1.07077846e+00 6.76281130e-02
 2.53605424e-02 1.17200000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1172 1149 1123
177.441 118.294 177.441
[1.12713522e-01 5.63567608e-03 1.07077846e+00 6.76281130e-02
 2.53605424e-02 1.17200000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1172 1149 110

1110 1236 1102
88.7205 118.294 -1.0
[3.38140565e-02 4.17040030e-01 4.28311382e+00 2.70512452e-01
 2.81783804e-02 1.11000000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1110 1236 1119
88.7205 118.294 -1.0
[3.38140565e-02 4.17040030e-01 4.28311382e+00 2.70512452e-01
 2.81783804e-02 1.11000000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1110 1236 1085
88.7205 118.294 -1.0
[3.38140565e-02 4.17040030e-01 4.28311382e+00 2.70512452e-01
 2.81783804e-02 1.11000000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1110 1236 1077
88.7205 118.294 -1.0
[3.38140565e-02 4.17040030e-01 4.28311382e+00 2.70512452e-01
 2.81783804e-02 1.11000000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1110 1236 1068
88.7205 118.294 -1.0
[3.38140565e-02 4.17040030e-01 4.28311382e+00 2.70512452e-01
 2.81783804e-02 1.11000000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1110 1238 1223
88.7205 11

1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1110 1266 1119
88.7205 177.441 -1.0
[3.38140565e-02 4.17040030e-01 4.28311382e+00 2.70512452e-01
 2.81783804e-02 1.11000000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1110 1266 1085
88.7205 177.441 -1.0
[3.38140565e-02 4.17040030e-01 4.28311382e+00 2.70512452e-01
 2.81783804e-02 1.11000000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1110 1266 1077
88.7205 177.441 -1.0
[3.38140565e-02 4.17040030e-01 4.28311382e+00 2.70512452e-01
 2.81783804e-02 1.11000000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1110 1266 1068
88.7205 177.441 -1.0
[3.38140565e-02 4.17040030e-01 4.28311382e+00 2.70512452e-01
 2.81783804e-02 1.11000000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1110 1293 1276
88.7205 118.294 236.588
[3.38140565e-02 4.17040030e-01 4.28311382e+00 2.70512452e-01
 2.81783804e-02 1.11000000e+03 0.00000000e+00]
1
((300, 610), (50, 27

88.7205 177.441 -1.0
[3.38140565e-02 4.17040030e-01 4.28311382e+00 2.70512452e-01
 2.81783804e-02 1.11000000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1110 1172 1068
88.7205 177.441 -1.0
[3.38140565e-02 4.17040030e-01 4.28311382e+00 2.70512452e-01
 2.81783804e-02 1.11000000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1110 1123 1102
88.7205 177.441 -1.0
[3.38140565e-02 4.17040030e-01 4.28311382e+00 2.70512452e-01
 2.81783804e-02 1.11000000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1110 1123 1119
88.7205 177.441 -1.0
[3.38140565e-02 4.17040030e-01 4.28311382e+00 2.70512452e-01
 2.81783804e-02 1.11000000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1110 1123 1085
88.7205 177.441 -1.0
[3.38140565e-02 4.17040030e-01 4.28311382e+00 2.70512452e-01
 2.81783804e-02 1.11000000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (0, 2))
[300. 150.   1.]
1110 1123 1077
88.7205 177.441 -1.0
[3.3

1123 1240 1156
177.441 118.294 118.294
[5.63567608e-03 1.18349198e-01 1.07077846e+00 6.76281130e-02
 5.63567608e-03 1.12300000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1123 1240 1182
177.441 118.294 118.294
[5.63567608e-03 1.18349198e-01 1.07077846e+00 6.76281130e-02
 5.63567608e-03 1.12300000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1123 1240 1146
177.441 118.294 118.294
[5.63567608e-03 1.18349198e-01 1.07077846e+00 6.76281130e-02
 5.63567608e-03 1.12300000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1123 1240 1149
177.441 118.294 118.294
[5.63567608e-03 1.18349198e-01 1.07077846e+00 6.76281130e-02
 5.63567608e-03 1.12300000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 100.]
1123 1240 1172
177.441 118.294 177.441
[5.63567608e-03 1.18349198e-01 1.07077846e+00 6.76281130e-02
 5.63567608e-03 1.12300000e+03 0.00000000e+00]
1
((300, 610), (50, 270), (50, 270))
[300. 150. 1

1102 1208 1156
-1.0 709.764 118.294
[  24.   67.  490.   14.    8. 1102.    2.]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1102 1208 1182
-1.0 709.764 118.294
[  24.   67.  490.   14.    8. 1102.    2.]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1102 1208 1146
-1.0 709.764 118.294
[  24.   67.  490.   14.    8. 1102.    2.]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1102 1208 1149
-1.0 709.764 118.294
[  24.   67.  490.   14.    8. 1102.    2.]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1102 1208 1172
-1.0 709.764 177.441
[  24.   67.  490.   14.    8. 1102.    2.]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1102 1208 1110
-1.0 709.764 88.7205
[  24.   67.  490.   14.    8. 1102.    2.]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1102 1208 1123
-1.0 709.764 177.441
[  24.   67.  490.   14.    8. 1102.    2.]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1102 1208 1119
-1.0 709.764 -1.0
[  24.   67.  490.   14.    8. 1102.    2.]
((0, 2), (50, 270), (0, 2))

1102 1156 1110
-1.0 118.294 88.7205
[  24.   67.  490.   14.    8. 1102.    2.]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1102 1156 1123
-1.0 118.294 177.441
[  24.   67.  490.   14.    8. 1102.    2.]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1102 1156 1119
-1.0 118.294 -1.0
[  24.   67.  490.   14.    8. 1102.    2.]
((0, 2), (50, 270), (0, 2))
[  1. 150.   1.]
1102 1156 1085
-1.0 118.294 -1.0
[  24.   67.  490.   14.    8. 1102.    2.]
((0, 2), (50, 270), (0, 2))
[  1. 150.   1.]
1102 1156 1077
-1.0 118.294 -1.0
[  24.   67.  490.   14.    8. 1102.    2.]
((0, 2), (50, 270), (0, 2))
[  1. 150.   1.]
1102 1156 1068
-1.0 118.294 -1.0
[  24.   67.  490.   14.    8. 1102.    2.]
((0, 2), (50, 270), (0, 2))
[  1. 150.   1.]
1102 1182 1146
-1.0 118.294 118.294
[  24.   67.  490.   14.    8. 1102.    2.]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1102 1182 1149
-1.0 118.294 118.294
[  24.   67.  490.   14.    8. 1102.    2.]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]


1119 1223 1123
-1.0 157.7253333 177.441
[  26.   67.  550.   19.   10. 1119.    2.]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1119 1223 1102
-1.0 157.7253333 -1.0
[  26.   67.  550.   19.   10. 1119.    2.]
((0, 2), (50, 270), (0, 2))
[  1. 150.   1.]
1119 1223 1085
-1.0 157.7253333 -1.0
[  26.   67.  550.   19.   10. 1119.    2.]
((0, 2), (50, 270), (0, 2))
[  1. 150.   1.]
1119 1223 1077
-1.0 157.7253333 -1.0
[  26.   67.  550.   19.   10. 1119.    2.]
((0, 2), (50, 270), (0, 2))
[  1. 150.   1.]
1119 1223 1068
-1.0 157.7253333 -1.0
[  26.   67.  550.   19.   10. 1119.    2.]
((0, 2), (50, 270), (0, 2))
[  1. 150.   1.]
1119 1240 1266
-1.0 118.294 177.441
[  26.   67.  550.   19.   10. 1119.    2.]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1119 1240 1293
-1.0 118.294 118.294
[  26.   67.  550.   19.   10. 1119.    2.]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1119 1240 1276
-1.0 118.294 236.588
[  26.   67.  550.   19.   10. 1119.    2.]
((0, 2), (50, 270), (50, 270

1119 1182 1085
-1.0 118.294 -1.0
[  26.   67.  550.   19.   10. 1119.    2.]
((0, 2), (50, 270), (0, 2))
[  1. 150.   1.]
1119 1182 1077
-1.0 118.294 -1.0
[  26.   67.  550.   19.   10. 1119.    2.]
((0, 2), (50, 270), (0, 2))
[  1. 150.   1.]
1119 1182 1068
-1.0 118.294 -1.0
[  26.   67.  550.   19.   10. 1119.    2.]
((0, 2), (50, 270), (0, 2))
[  1. 150.   1.]
1119 1146 1149
-1.0 118.294 118.294
[  26.   67.  550.   19.   10. 1119.    2.]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1119 1146 1172
-1.0 118.294 177.441
[  26.   67.  550.   19.   10. 1119.    2.]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1119 1146 1110
-1.0 118.294 88.7205
[  26.   67.  550.   19.   10. 1119.    2.]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1119 1146 1123
-1.0 118.294 177.441
[  26.   67.  550.   19.   10. 1119.    2.]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1119 1146 1102
-1.0 118.294 -1.0
[  26.   67.  550.   19.   10. 1119.    2.]
((0, 2), (50, 270), (0, 2))
[  1. 150.   1.]


1085 1238 1156
-1.0 118.294 118.294
[  11.    33.   270.    11.     3.5 1085.     2. ]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1085 1238 1182
-1.0 118.294 118.294
[  11.    33.   270.    11.     3.5 1085.     2. ]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1085 1238 1146
-1.0 118.294 118.294
[  11.    33.   270.    11.     3.5 1085.     2. ]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1085 1238 1149
-1.0 118.294 118.294
[  11.    33.   270.    11.     3.5 1085.     2. ]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1085 1238 1172
-1.0 118.294 177.441
[  11.    33.   270.    11.     3.5 1085.     2. ]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1085 1238 1110
-1.0 118.294 88.7205
[  11.    33.   270.    11.     3.5 1085.     2. ]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1085 1238 1123
-1.0 118.294 177.441
[  11.    33.   270.    11.     3.5 1085.     2. ]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1085 1238 1102
-1.0 118.294 -1.0
[  11.    33.   270.  

1085 1156 1077
-1.0 118.294 -1.0
[  11.    33.   270.    11.     3.5 1085.     2. ]
((0, 2), (50, 270), (0, 2))
[  1. 150.   1.]
1085 1156 1068
-1.0 118.294 -1.0
[  11.    33.   270.    11.     3.5 1085.     2. ]
((0, 2), (50, 270), (0, 2))
[  1. 150.   1.]
1085 1182 1146
-1.0 118.294 118.294
[  11.    33.   270.    11.     3.5 1085.     2. ]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1085 1182 1149
-1.0 118.294 118.294
[  11.    33.   270.    11.     3.5 1085.     2. ]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1085 1182 1172
-1.0 118.294 177.441
[  11.    33.   270.    11.     3.5 1085.     2. ]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1085 1182 1110
-1.0 118.294 88.7205
[  11.    33.   270.    11.     3.5 1085.     2. ]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1085 1182 1123
-1.0 118.294 177.441
[  11.    33.   270.    11.     3.5 1085.     2. ]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1085 1182 1102
-1.0 118.294 -1.0
[  11.    33.   270.    11.     3.

1077 1238 1293
-1.0 118.294 118.294
[  12.   32.  240.    8.    3. 1077.    2.]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1077 1238 1276
-1.0 118.294 236.588
[  12.   32.  240.    8.    3. 1077.    2.]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1077 1238 1156
-1.0 118.294 118.294
[  12.   32.  240.    8.    3. 1077.    2.]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1077 1238 1182
-1.0 118.294 118.294
[  12.   32.  240.    8.    3. 1077.    2.]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1077 1238 1146
-1.0 118.294 118.294
[  12.   32.  240.    8.    3. 1077.    2.]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1077 1238 1149
-1.0 118.294 118.294
[  12.   32.  240.    8.    3. 1077.    2.]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1077 1238 1172
-1.0 118.294 177.441
[  12.   32.  240.    8.    3. 1077.    2.]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1077 1238 1110
-1.0 118.294 88.7205
[  12.   32.  240.    8.    3. 1077.    2.]
((0, 2), (50, 270), (50,

[  1. 150. 100.]
1077 1156 1149
-1.0 118.294 118.294
[  12.   32.  240.    8.    3. 1077.    2.]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1077 1156 1172
-1.0 118.294 177.441
[  12.   32.  240.    8.    3. 1077.    2.]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1077 1156 1110
-1.0 118.294 88.7205
[  12.   32.  240.    8.    3. 1077.    2.]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1077 1156 1123
-1.0 118.294 177.441
[  12.   32.  240.    8.    3. 1077.    2.]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1077 1156 1102
-1.0 118.294 -1.0
[  12.   32.  240.    8.    3. 1077.    2.]
((0, 2), (50, 270), (0, 2))
[  1. 150.   1.]
1077 1156 1119
-1.0 118.294 -1.0
[  12.   32.  240.    8.    3. 1077.    2.]
((0, 2), (50, 270), (0, 2))
[  1. 150.   1.]
1077 1156 1085
-1.0 118.294 -1.0
[  12.   32.  240.    8.    3. 1077.    2.]
((0, 2), (50, 270), (0, 2))
[  1. 150.   1.]
1077 1156 1068
-1.0 118.294 -1.0
[  12.   32.  240.    8.    3. 1077.    2.]
((0, 2), (50, 270), (0, 2))


-1.0 709.764 -1.0
[  10.    34.   250.    10.     2.5 1068.     2. ]
((0, 2), (50, 270), (0, 2))
[  1. 150.   1.]
1068 1208 1085
-1.0 709.764 -1.0
[  10.    34.   250.    10.     2.5 1068.     2. ]
((0, 2), (50, 270), (0, 2))
[  1. 150.   1.]
1068 1208 1077
-1.0 709.764 -1.0
[  10.    34.   250.    10.     2.5 1068.     2. ]
((0, 2), (50, 270), (0, 2))
[  1. 150.   1.]
1068 1236 1238
-1.0 118.294 118.294
[  10.    34.   250.    10.     2.5 1068.     2. ]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1068 1236 1223
-1.0 118.294 157.7253333
[  10.    34.   250.    10.     2.5 1068.     2. ]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1068 1236 1240
-1.0 118.294 118.294
[  10.    34.   250.    10.     2.5 1068.     2. ]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1068 1236 1266
-1.0 118.294 177.441
[  10.    34.   250.    10.     2.5 1068.     2. ]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1068 1236 1293
-1.0 118.294 118.294
[  10.    34.   250.    10.     2.5 1068.     2.

1068 1293 1276
-1.0 118.294 236.588
[  10.    34.   250.    10.     2.5 1068.     2. ]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1068 1293 1156
-1.0 118.294 118.294
[  10.    34.   250.    10.     2.5 1068.     2. ]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1068 1293 1182
-1.0 118.294 118.294
[  10.    34.   250.    10.     2.5 1068.     2. ]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1068 1293 1146
-1.0 118.294 118.294
[  10.    34.   250.    10.     2.5 1068.     2. ]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1068 1293 1149
-1.0 118.294 118.294
[  10.    34.   250.    10.     2.5 1068.     2. ]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1068 1293 1172
-1.0 118.294 177.441
[  10.    34.   250.    10.     2.5 1068.     2. ]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1068 1293 1110
-1.0 118.294 88.7205
[  10.    34.   250.    10.     2.5 1068.     2. ]
((0, 2), (50, 270), (50, 270))
[  1. 150. 100.]
1068 1293 1123
-1.0 118.294 177.441
[  10.    34.   250

1068 1102 1119
-1.0 -1.0 -1.0
[  10.    34.   250.    10.     2.5 1068.     2. ]
((0, 2), (0, 2), (0, 2))
[1. 1. 1.]
1068 1102 1085
-1.0 -1.0 -1.0
[  10.    34.   250.    10.     2.5 1068.     2. ]
((0, 2), (0, 2), (0, 2))
[1. 1. 1.]
1068 1102 1077
-1.0 -1.0 -1.0
[  10.    34.   250.    10.     2.5 1068.     2. ]
((0, 2), (0, 2), (0, 2))
[1. 1. 1.]
1068 1119 1085
-1.0 -1.0 -1.0
[  10.    34.   250.    10.     2.5 1068.     2. ]
((0, 2), (0, 2), (0, 2))
[1. 1. 1.]
1068 1119 1077
-1.0 -1.0 -1.0
[  10.    34.   250.    10.     2.5 1068.     2. ]
((0, 2), (0, 2), (0, 2))
[1. 1. 1.]
1068 1085 1077
-1.0 -1.0 -1.0
[  10.    34.   250.    10.     2.5 1068.     2. ]
((0, 2), (0, 2), (0, 2))
[1. 1. 1.]


In [210]:
ccc = [1156, 1149, 1068]
p = dish[dish.pk == ccc[0]]['protein'].values/dish[dish.pk == ccc[0]]['portion_volume'].values*469.5 +\
dish[dish.pk == ccc[1]]['protein'].values/dish[dish.pk == ccc[1]]['portion_volume'].values*202+\
dish[dish.pk == ccc[2]]['protein'].values/dish[dish.pk == ccc[2]]['portion_volume'].values*-1*2


carbs = dish[dish.pk == ccc[0]]['carbohydrate'].values/dish[dish.pk == ccc[0]]['portion_volume'].values*469.5 +\
dish[dish.pk == ccc[1]]['carbohydrate'].values/dish[dish.pk == ccc[1]]['portion_volume'].values*202+\
dish[dish.pk == ccc[2]]['carbohydrate'].values/dish[dish.pk == ccc[2]]['portion_volume'].values*-1*2

calo = dish[dish.pk == ccc[0]]['calories'].values/dish[dish.pk == ccc[0]]['portion_volume'].values*469.5 +\
dish[dish.pk == ccc[1]]['calories'].values/dish[dish.pk == ccc[1]]['portion_volume'].values*202+\
dish[dish.pk == ccc[2]]['calories'].values/dish[dish.pk == ccc[2]]['portion_volume'].values*-1*2

tfat = dish[dish.pk == ccc[0]]['total_fat'].values/dish[dish.pk == ccc[0]]['portion_volume'].values*469.5 +\
dish[dish.pk == ccc[1]]['total_fat'].values/dish[dish.pk == ccc[1]]['portion_volume'].values*202+\
dish[dish.pk == ccc[2]]['total_fat'].values/dish[dish.pk == ccc[2]]['portion_volume'].values*-1*2

print(p, carbs, calo, tfat)

[47.228769] [171.28503559] [1129.95587266] [33.91448425]


In [152]:
[ 45.81006644,  180.86883527, 1126.54961367,   26.29986305,8]

47.232

In [193]:
itemm = [1156, 1149, 1068]
cc = []
for iii in itemm:
    protein, carbohydrate, calories, total_fat, saturated_fat, portion_volume, max_pieces = dish[dish.pk == iii][['protein', 'carbohydrate', 'calories', 'total_fat', 'saturated_fat', 'portion_volume', 'max_pieces']].values.squeeze(0)
    mm = dish_nutrient(protein, carbohydrate, calories, total_fat, saturated_fat, portion_volume, iii, max_pieces)
    cc.append(mm)


In [194]:
print(pick_meal(cc))

((100, 610), (50, 270), (0, 2))
[300. 150.   1.]
[1156, 1149, 1068, 158.0, 270.0, 2.0, array([ 32.57882902, 126.66738803, 865.69902108,  30.65988131,
         5.        ]), 95310.03029916059]
